# Generated by Django 3.0.5 on 2022-05-09 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beds',
            fields=[
                ('bedId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bedStatus', models.BooleanField(default=False)),
                ('patientId', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
